import type { Metadata } from "next";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextAuthProvider from "@/providers/auth.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster duration={1500} expand={true} position="top-right" />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
